package com.autorepair.common.error;

public enum ErrorCode {
    ERR_AUTH_UNAUTHORIZED,
    ERR_AUTH_FORBIDDEN,
    ERR_AUTH_TENANT_MISSING,
    ERR_AUTH_BRANCH_REQUIRED,
    ERR_AUTH_MEMBERSHIP_UNKNOWN,
    ERR_PERMISSION_DENIED,
    ERR_OWNERSHIP_DENIED,
    ERR_VALIDATION_FAILED,
    ERR_RESOURCE_NOT_FOUND,
    ERR_RESOURCE_CONFLICT,
    ERR_POLICY_INVALID_SCHEMA,
    ERR_IDEMPOTENCY_HASH_MISMATCH,
    ERR_IDEMPOTENCY_REPLAY,
    ERR_DUPLICATE_PLATE,
    ERR_FILE_NOT_ALLOWED,
    ERR_FILE_TOO_LARGE,
    ERR_WEBHOOK_SIGNATURE_INVALID,
    ERR_RATE_LIMITED,
    ERR_PRECONDITION_REQUIRED,
    ERR_INTERNAL
}
